// examples/vue/LiveLLMChat.vue
<!--
  LiveLLM Vue Integration Example

  This shows how to use LiveLLM with Vue 3 to render
  interactive LLM responses.

  Install: npm install livellm
-->
<template>
  <div class="livellm-chat">
    <!-- Rendered output -->
    <div ref="outputRef" class="livellm-output" @livellm:action="handleAction" />

    <!-- Input form -->
    <form @submit.prevent="handleSubmit">
      <input
        v-model="input"
        type="text"
        placeholder="Ask something..."
      />
      <button type="submit" :disabled="!input.trim()">Send</button>
    </form>
  </div>
</template>

<script setup lang="ts">
import { ref, watch, onMounted, onUnmounted } from 'vue';
import LiveLLM from 'livellm';

interface Message {
  role: 'user' | 'assistant';
  content: string;
}

const outputRef = ref<HTMLDivElement>();
const input = ref('');
const messages = ref<Message[]>([]);

// Render assistant messages whenever they change
watch(
  () => messages.value.filter(m => m.role === 'assistant'),
  (assistantMsgs) => {
    if (!outputRef.value) return;
    const markdown = assistantMsgs.map(m => m.content).join('\n\n');
    if (markdown) {
      outputRef.value.innerHTML = LiveLLM.render(markdown);
    }
  },
  { deep: true }
);

// Action handler
function handleAction(e: Event) {
  const detail = (e as CustomEvent).detail;
  console.log('LiveLLM Action:', detail);
  // Send action back to LLM or handle locally
}

// Set up global action handler
onMounted(() => {
  LiveLLM.actions.onAction((action) => {
    console.log('User action:', action);
  });
});

async function handleSubmit() {
  if (!input.value.trim()) return;

  messages.value.push({ role: 'user', content: input.value });
  input.value = '';

  // Example: Call your LLM API here
  // const response = await fetch('/api/chat', { ... });
  // messages.value.push({ role: 'assistant', content: response.text });
}
</script>

<!--
  LiveLLM Streaming Example (composable)

  Usage in your component:
    const { containerRef, startStream } = useLiveLLMStream();

  <template>
    <div ref="containerRef" />
    <button @click="startStream('/api/stream')">Start</button>
  </template>
-->
<script lang="ts">
// Composable for streaming
export function useLiveLLMStream() {
  const containerRef = ref<HTMLDivElement>();

  async function startStream(url: string, body?: Record<string, any>) {
    if (!containerRef.value) return;

    const sr = LiveLLM.createStream({
      container: containerRef.value,
      onComplete: (html: string) => {
        console.log('Stream complete', html.length, 'chars');
      },
    });

    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(body || {}),
    });

    if (response.body) {
      const reader = response.body.pipeThrough(new TextDecoderStream());
      sr.connectReadableStream(reader.readable);
    }
  }

  return { containerRef, startStream };
}

// Composable for observer mode
export function useLiveLLMObserver() {
  const containerRef = ref<HTMLDivElement>();

  onMounted(() => {
    if (containerRef.value) {
      LiveLLM.observe({ target: containerRef.value });
    }
  });

  onUnmounted(() => {
    LiveLLM.disconnect();
  });

  return { containerRef };
}
</script>

// examples/svelte/LiveLLMChat.svelte
<!--
  LiveLLM Svelte Integration Example

  This shows how to use LiveLLM with Svelte to render
  interactive LLM responses.

  Install: npm install livellm
-->
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import LiveLLM from 'livellm';

  interface Message {
    role: 'user' | 'assistant';
    content: string;
  }

  let outputEl: HTMLDivElement;
  let input = '';
  let messages: Message[] = [];
  let streaming = false;

  // Render messages reactively
  $: {
    const assistantContent = messages
      .filter(m => m.role === 'assistant')
      .map(m => m.content)
      .join('\n\n');

    if (outputEl && assistantContent) {
      outputEl.innerHTML = LiveLLM.render(assistantContent);
    }
  }

  onMount(() => {
    // Set up global action handler
    LiveLLM.actions.onAction((action) => {
      console.log('User action:', action);
      // Handle action — e.g., send back to LLM
    });
  });

  function handleAction(e: CustomEvent) {
    console.log('LiveLLM Action:', e.detail);
  }

  async function handleSubmit() {
    if (!input.trim()) return;

    messages = [...messages, { role: 'user', content: input }];
    input = '';

    // Example: Call your LLM API here
    // const response = await fetch('/api/chat', { ... });
    // messages = [...messages, { role: 'assistant', content: response.text }];
  }

  async function handleStreamSubmit() {
    if (!input.trim() || streaming) return;

    const userInput = input;
    input = '';
    streaming = true;

    const sr = LiveLLM.createStream({
      container: outputEl,
      onComplete: () => {
        streaming = false;
        console.log('Stream complete');
      },
    });

    try {
      const response = await fetch('/api/chat/stream', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: userInput }),
      });

      if (response.body) {
        const reader = response.body.pipeThrough(new TextDecoderStream());
        sr.connectReadableStream(reader.readable);
      }
    } catch (err) {
      streaming = false;
      console.error('Stream error:', err);
    }
  }
</script>

<div class="livellm-chat">
  <!-- Rendered output -->
  <div
    bind:this={outputEl}
    class="livellm-output"
    on:livellm:action={handleAction}
  />

  <!-- Input form -->
  <form on:submit|preventDefault={handleSubmit}>
    <input
      type="text"
      bind:value={input}
      placeholder="Ask something..."
    />
    <button type="submit" disabled={!input.trim()}>Send</button>
    <button type="button" on:click={handleStreamSubmit} disabled={streaming}>
      {streaming ? 'Streaming...' : 'Stream'}
    </button>
  </form>
</div>

<style>
  .livellm-chat {
    max-width: 800px;
    margin: 0 auto;
  }
  .livellm-output {
    min-height: 200px;
    padding: 16px;
  }
  form {
    display: flex;
    gap: 8px;
    padding: 16px;
    border-top: 1px solid #e0e0e0;
  }
  input {
    flex: 1;
    padding: 8px 12px;
    border: 1px solid #e0e0e0;
    border-radius: 6px;
    font-size: 14px;
  }
  button {
    padding: 8px 16px;
    border: none;
    border-radius: 6px;
    background: #6c5ce7;
    color: white;
    cursor: pointer;
    font-size: 14px;
  }
  button:disabled {
    opacity: 0.5;
    cursor: not-allowed;
  }
</style>
